Feature/species entry validation
TurtleCubed/Custom-eBird-Quiz pull request #8
Opened 2023-09-10 03:12 UTC by TurtleCubed

2023-09-10 19:48 UTC, aaronsun1030 requested changes

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/species_validation.py
> +from pandas import DataFrame
pandas seems like overkill just to read a csv, why not use built-in `csv` library instead? Will pandas be used in other places?

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/species_validation.py
> +from fast_autocomplete import AutoComplete
Not in `requirements.txt`, nor is it ever used. Also there's already an autocomplete box functionality `AutocompleteEntryListbox` which I would check out.

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/QuizFrontend.py
> +        im = self.resize_to_tk(Image.open("./BirdQuiz/resources/intro.jpg"))
I think we should assume that the code is run in the `BirdQuiz` directory.

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/species_validation.py
> +        if not os.path.isfile("BirdQuiz/resources/" + CHECKLIST_NAME):
(repetitive) I think we should assume that the code is run in the `BirdQuiz` directory.

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/species_validation.py
> +        with open(CHECKLIST_NAME, "wb") as f:
Saves to base directory, not `resources` directory.

2023-09-10 19:48 UTC, aaronsun1030 commented on BirdQuiz/QuizFrontend.py
> +        self.root.bind('<Return>', lambda i=inputbox, l=listbox: self.add_to_listbox(i, l))
Errors on return, need an extra argument in lambda function

2023-09-10 20:38 UTC, aaronsun1030 commented
Weird bug with `.title()` not handling apostrophes well:

Capitalizes after apostrophe (baird's sandpiper -> Baird'S Sandpiper), see [stack overflow](https://stackoverflow.com/questions/8199966/python-title-with-apostrophes).

After inputting this, nothing works anymore. Also, bizarre ghost printing:

```
S is an invalid species name
S
Baird'S Sandpiper is an invalid species name
S
Baird'S Sandpiper
Mallard is an invalid species name
S
Baird'S Sandpiper
Mallard
Baird'S Sandpiper is an invalid species name
```

2023-09-11 04:38 UTC, TurtleCubed commented on BirdQuiz/species_validation.py
> +from pandas import DataFrame
pandas will be used in other places, should I leave it out of this branch and only add it when necessary?

2023-09-11 04:39 UTC, TurtleCubed commented on BirdQuiz/species_validation.py
> +from fast_autocomplete import AutoComplete
My bad on this one. I was testing out fast_autocomplete for a different feature.

2023-09-11 04:42 UTC, TurtleCubed commented on BirdQuiz/QuizFrontend.py
> +        im = self.resize_to_tk(Image.open("./BirdQuiz/resources/intro.jpg"))
kk, will change

2023-09-11 04:58 UTC, TurtleCubed commented on BirdQuiz/species_validation.py
> +        if not os.path.isfile("BirdQuiz/resources/" + CHECKLIST_NAME):
done

2023-09-11 04:59 UTC, TurtleCubed commented on BirdQuiz/species_validation.py
> +        with open(CHECKLIST_NAME, "wb") as f:
yep got that in another commit

2023-09-11 05:02 UTC, TurtleCubed commented on BirdQuiz/QuizFrontend.py
> +        self.root.bind('<Return>', lambda i=inputbox, l=listbox: self.add_to_listbox(i, l))
that's really odd, but I got that too

2023-09-11 05:08 UTC, TurtleCubed commented
> Weird bug with `.title()` not handling apostrophes well:
> 
> Capitalizes after apostrophe (baird's sandpiper -> Baird'S Sandpiper), see [stack overflow](https://stackoverflow.com/questions/8199966/python-title-with-apostrophes).
> 
> After inputting this, nothing works anymore. Also, bizarre ghost printing:
> 
> ```
> S is an invalid species name
> S
> Baird'S Sandpiper is an invalid species name
> S
> Baird'S Sandpiper
> Mallard is an invalid species name
> S
> Baird'S Sandpiper
> Mallard
> Baird'S Sandpiper is an invalid species name
> ```

Regarding this: The issue was that upon failing validation, the inputbox would not clear. The ghost printing was from the inputbox having an extra line containing the previous incorrect string.

2023-09-11 10:41 UTC, aaronsun1030 commented on BirdQuiz/species_validation.py
> +from pandas import DataFrame
no IDC

2023-09-11 10:47 UTC, aaronsun1030 commented on BirdQuiz/QuizFrontend.py
> +        text = inputbox.get("1.0", "end").strip()
I like the auto-capitalization, so can you add `capwords` like they recommend in [this post](https://stackoverflow.com/questions/8199966/python-title-with-apostrophes)?

2023-09-11 15:32 UTC, aaronsun1030 commented on BirdQuiz/QuizFrontend.py
> +        text = inputbox.get("1.0", "end").strip()
to be fixed in next PR

2023-09-11 15:32 UTC, merged